#=======================================================
#                  Orion | Anti-Cheat                  =
#                      by OrionPvP                       =
#=======================================================

# Do Not Touch Any Settings

options:
	version:
	link: "LINK_BROKEN"

on join:
	player has permission "orion.admin":
		wait 3 seconds
		if text from "" = "{@version}":
			stop
		else:
			set {_vers} to text from ""
			send "&3-----------------------------------------" to player
			send "%{logo}% &7I have found an update for my file" to player
			send "&7You can download it at: &6{@link}" to player
			send "&7Current version: &6{@version}" to player
			send "&7Newest version: &6%{_vers}%" to player
			send "&7Thank you for using &3Orion AC" to player
			send "&3-----------------------------------------" to player
			stop

on load:
	#-------------------------
	# Main file
	#-------------------------
	if folder "plugins/Orion/" doesn't exists:
		create folder "plugins/Orion/"
	#-------------------------
	# Languages file
	#-------------------------
	if folder "plugins/Orion/languages" doesn't exists:
		create folder "plugins/Orion/languages"
	#-------------------------
	# Config
	#-------------------------
	if file "plugins/Orion/config.yml" doesn't exists:
		create file "plugins/Orion/config.yml"
		wf "##Orion | Anti-Cheat" to "plugins/Orion/config.yml"
		wf "##Main settings:" to "plugins/Orion/config.yml"
		set "Logo" to "&7[&4ϟ&7]&3&lOrion&7»" in yaml file "plugins/Orion/config.yml"
		wf "##Orion banning?" to "plugins/Orion/config.yml"
		wf "##Leave this to true if you are not using other plugin for banning!" to "plugins/Orion/config.yml"
		set "Orion banning" to "true" in yaml file "plugins/Orion/config.yml"
		wf "##If above is false no need for this to be changed!" to "plugins/Orion/config.yml"
		wf "##Do not add stuff such as player and reason, they will be auto added!" to "plugins/Orion/config.yml"
		set "Custom Ban CMD" to "/ban" in yaml file "plugins/Orion/config.yml"
		wf "##Ban messages" to "plugins/Orion/config.yml"
		set "BanMSG" to "&3&lOrion&7» &2You are banned for &e" in yaml file "plugins/Orion/config.yml"
		set "BanMSG 2" to "&2You can appeal at: &awww.yourwebsite.com" in yaml file "plugins/Orion/config.yml"
		set "BanMSG 3" to "&3Orion AC" in yaml file "plugins/Orion/config.yml"
	#-------------------------
	# Checks
	#-------------------------
	if file "plugins/Orion/checks.yml" doesn't exists:
		create file "plugins/Orion/checks.yml"
		wf "##Checks:" to "plugins/Orion/checks.yml"
		wf "##(After how many checks should players get auto banned?)" to "plugins/Orion/checks.yml"
		set "Kill Aura Checks" to "10" in yaml file "plugins/Orion/checks.yml"
		set "Auto Clicker Checks" to "10" in yaml file "plugins/Orion/checks.yml"
		set "Fly Checks" to "20" in yaml file "plugins/Orion/checks.yml"
		set "Jesus Checks" to "20" in yaml file "plugins/Orion/checks.yml"
		set "Speed Checks" to "20" in yaml file "plugins/Orion/checks.yml"
		set "AntiKB Checks" to "10" in yaml file "plugins/Orion/checks.yml"
		set "Phase Checks" to "10" in yaml file "plugins/Orion/checks.yml"
		set "Auto Sneak Checks" to "15" in yaml file "plugins/Orion/checks.yml"
		set "Fast Build Checks" to "20" in yaml file "plugins/Orion/checks.yml"
		set "Fast Break Checks" to "20" in yaml file "plugins/Orion/checks.yml"
		set "Fast Bow Checks" to "10" in yaml file "plugins/Orion/checks.yml"
		set "Multi Aura Checks" to "10" in yaml file "plugins/Orion/checks.yml"
	#-------------------------
	# Settings
	#-------------------------
	if file "plugins/Orion/settings.yml" doesn't exists:
		create file "plugins/Orion/settings.yml"
		wf "##Settings for certain hacks" to "plugins/Orion/settings.yml"
		set "Max Ping" to "200" in yaml file "plugins/Orion/settings.yml"
		set "Kill Aura range" to "5.31" in yaml file "plugins/Orion/settings.yml"
		set "Max Clicks per second" to "17" in yaml file "plugins/Orion/settings.yml"
		set "Max speed of eating (seconds)" to "1.65" in yaml file "plugins/Orion/settings.yml"
		set "Max speed of regenerating (seconds)" to "0.5" in yaml file "plugins/Orion/settings.yml"
		set "Max speed of breaking blocks (seconds)" to "0.13" in yaml file "plugins/Orion/settings.yml"
		set "Max speed of placing blocks (seconds)" to "0.13" in yaml file "plugins/Orion/settings.yml"
		set "Max speed of shooting arrows (seconds)" to "0.195" in yaml file "plugins/Orion/settings.yml"
		set "Max speed of moving per second (blocks)" to "8" in yaml file "plugins/Orion/settings.yml"
		set "Anti Bot" to "true" in yaml file "plugins/Orion/settings.yml"
	#-------------------------
	# Messages
	#-------------------------
	if file "plugins/Orion/messages.yml" doesn't exists:
		create file "plugins/Orion/messages.yml"
		wf "##Messages for certain hacks" to "plugins/Orion/messages.yml"
		set "Check reports 1" to "&2Make sure to type: &e/reports <hack>" in yaml file "plugins/Orion/messages.yml"
		set "Check reports 2" to "&a(killaura, reach, fly, jesus, antikb, speed, fastbuild, fastbreak)" in yaml file "plugins/Orion/messages.yml"
		set "Report sent" to "&aReport has been sent!" in yaml file "plugins/Orion/messages.yml"
		set "Cleared reports" to "&aReports have been cleared!" in yaml file "plugins/Orion/messages.yml"
		set "Unsolved reports" to "&eUnsolved reports:" in yaml file "plugins/Orion/messages.yml"


		set "Main alert color 1" to "&2" in yaml file "plugins/Orion/messages.yml"
		set "Main alert color 2" to "&7" in yaml file "plugins/Orion/messages.yml"
		set "Main alert color 3" to "&a" in yaml file "plugins/Orion/messages.yml"

		set "Cannot ban" to "&cYou cannot ban this player!" in yaml file "plugins/Orion/messages.yml"
		set "Cannot kick" to "&cYou cannot kick this player!" in yaml file "plugins/Orion/messages.yml"

		set "Reset checks" to "&aReset stats of player!" in yaml file "plugins/Orion/messages.yml"
		set "Unbanned" to "&ewas unbanned by &a" in yaml file "plugins/Orion/messages.yml"

		set "Correct 1" to "&cPlease use &e/Orion ban <playername> <reason>" in yaml file "plugins/Orion/messages.yml"
		set "Correct 2" to "&cPlease use &e/Orion reset <playername>" in yaml file "plugins/Orion/messages.yml"
		set "Correct 3" to "&cPlease use &e/Orion unban <playername>" in yaml file "plugins/Orion/messages.yml"
		set "Correct 4" to "&cPlease use &e/Orion ip <playername>" in yaml file "plugins/Orion/messages.yml"
		set "Correct 5" to "&cPlease use &e/Orion kick <playername> <reason>" in yaml file "plugins/Orion/messages.yml"

		set "Alerts false" to "&eYou will no longer recieve alerts!" in yaml file "plugins/Orion/messages.yml"
		set "Alerts true" to "&eYou will now recieve alerts!" in yaml file "plugins/Orion/messages.yml"

		set "Total banned" to "&aTotal banned amount: &e" in yaml file "plugins/Orion/messages.yml"

		set "Help 1" to "&f&m---------[&3Orion&f&m]---------" in yaml file "plugins/Orion/messages.yml"
		set "Help 2" to "&3/Orion &fconfig" in yaml file "plugins/Orion/messages.yml"
		set "Help 3" to "&3/Orion &fjudgemental" in yaml file "plugins/Orion/messages.yml"
		set "Help 4" to "&3/Orion &ftestkb <player>" in yaml file "plugins/Orion/messages.yml"
		set "Help 5" to "&3/Orion &fban <player> <hack>" in yaml file "plugins/Orion/messages.yml"
		set "Help 6" to "&3/Orion &fkick <player> <reason>" in yaml file "plugins/Orion/messages.yml"
		set "Help 7" to "&3/Orion &freset <player>" in yaml file "plugins/Orion/messages.yml"
		set "Help 8" to "&3/Orion &fnotify" in yaml file "plugins/Orion/messages.yml"
		set "Help 9" to "&3/check &f<player>" in yaml file "plugins/Orion/messages.yml"
		set "Help 10" to "&f&m---------[&3Orion&f&m]---------" in yaml file "plugins/Orion/messages.yml"

		set "Banning mode" to "&7Banning mode is now set to " in yaml file "plugins/Orion/messages.yml"
		set "Settings off" to "Banwave &7is now turned &2OFF" in yaml file "plugins/Orion/messages.yml"
		set "Settings on" to "Banwave &7is now turned &2ON" in yaml file "plugins/Orion/messages.yml"

		set "Hack off" to "&7is now turned &2OFF" in yaml file "plugins/Orion/messages.yml"
		set "Hack on" to "&7is now turned &2ON" in yaml file "plugins/Orion/messages.yml"

		set "Judgemental broadcast" to "&7I am starting &6&lJudgemental &7day! (&aGood luck!&7)" in yaml file "plugins/Orion/messages.yml"
		set "Judgemental broadcast fail" to "&6Judgemental &7mode is disabled in &c/Orion config" in yaml file "plugins/Orion/messages.yml"
	#-------------------------
	# Messages variables
	#-------------------------
	set {checkreports1} to single value "Check reports 1" get of "plugins/Orion/messages.yml"
	set {checkreports2} to single value "Check reports 2" get of "plugins/Orion/messages.yml"
	set {reportsent} to single value "Report sent" get of "plugins/Orion/messages.yml"
	set {reportscleared} to single value "Cleared reports" get of "plugins/Orion/messages.yml"
	set {unsolved} to single value "Unsolved reports" get of "plugins/Orion/messages.yml"
	#
	set {maincolor1} to single value "Main alert color 1" get of "plugins/Orion/messages.yml"
	set {maincolor2} to single value "Main alert color 2" get of "plugins/Orion/messages.yml"
	set {maincolor3} to single value "Main alert color 3" get of "plugins/Orion/messages.yml"
	#
	set {cannotban} to single value "Cannot ban" get of "plugins/Orion/messages.yml"
	set {cannotkick} to single value "Cannot kick" get of "plugins/Orion/messages.yml"
	#
	set {resetchecks} to single value "Reset checks" get of "plugins/Orion/messages.yml"
	set {unbanned} to single value "Unbanned" get of "plugins/Orion/messages.yml"
	#
	set {correct1} to single value "Correct 1" get of "plugins/Orion/messages.yml"
	set {correct2} to single value "Correct 2" get of "plugins/Orion/messages.yml"
	set {correct3} to single value "Correct 3" get of "plugins/Orion/messages.yml"
	set {correct4} to single value "Correct 4" get of "plugins/Orion/messages.yml"
	#
	set {alertsfalse} to single value "Alerts false" get of "plugins/Orion/messages.yml"
	set {alertstrue} to single value "Alerts true" get of "plugins/Orion/messages.yml"
	#
	set {totalbanned} to single value "Total banned" get of "plugins/Orion/messages.yml"
	#
	set {help1} to single value "Help 1" get of "plugins/Orion/messages.yml"
	set {help2} to single value "Help 2" get of "plugins/Orion/messages.yml"
	set {help3} to single value "Help 3" get of "plugins/Orion/messages.yml"
	set {help4} to single value "Help 4" get of "plugins/Orion/messages.yml"
	set {help5} to single value "Help 5" get of "plugins/Orion/messages.yml"
	set {help6} to single value "Help 6" get of "plugins/Orion/messages.yml"
	set {help7} to single value "Help 7" get of "plugins/Orion/messages.yml"
	set {help8} to single value "Help 8" get of "plugins/Orion/messages.yml"
	set {help9} to single value "Help 9" get of "plugins/Orion/messages.yml"
	set {help10} to single value "Help 10" get of "plugins/Orion/messages.yml"

	set {banningmode} to single value "Banning mode" get of "plugins/Orion/messages.yml"
	set {bansettingsoff} to single value "Settings off" get of "plugins/Orion/messages.yml"
	set {bansettingson} to single value "Settings on" get of "plugins/Orion/messages.yml"

	set {hackoff} to single value "Hack off" get of "plugins/Orion/messages.yml"
	set {hackon} to single value "Hack on" get of "plugins/Orion/messages.yml"

	set {judgementalstart} to single value "Judgemental broadcast" get of "plugins/Orion/messages.yml"
	set {judgementalfail} to single value "Judgemental broadcast fail" get of "plugins/Orion/messages.yml"
	#-------------------------
	# Config variables
	#-------------------------
	set {logo} to single value "Logo" get of "plugins/Orion/config.yml"
	set {banmsg} to single value "BanMSG" get of "plugins/Orion/config.yml"
	set {banmsg2} to single value "BanMSG 2" get of "plugins/Orion/config.yml"
	set {banmsg3} to single value "BanMSG 3" get of "plugins/Orion/config.yml"
	set {orionban} to single value "Orion banning" get of "plugins/Orion/config.yml"
	set {customcmd} to single value "Custom Ban CMD" get of "plugins/Orion/config.yml"
	#-------------------------
	# Checks variables
	#-------------------------
	set {kachecks} to single value "Kill Aura Checks" get of "plugins/Orion/checks.yml"
	set {fastplacechecks} to single value "Fast Build Checks" get of "plugins/Orion/checks.yml"
	set {fastbreakchecks} to single value "Fast Break Checks" get of "plugins/Orion/checks.yml"
	set {fastbowchecks} to single value "Fast Bow Checks" get of "plugins/Orion/checks.yml"
	set {autoclickerchecks} to single value "Auto Clicker Checks" get of "plugins/Orion/checks.yml"
	set {flychecks} to single value "Fly Checks" get of "plugins/Orion/checks.yml"
	set {jesuschecks} to single value "Jesus Checks" get of "plugins/Orion/checks.yml"
	set {speedchecks} to single value "Speed Checks" get of "plugins/Orion/checks.yml"
	set {antikbchecks} to single value "AntiKB Checks" get of "plugins/Orion/checks.yml"
	set {phasechecks} to single value "Phase Checks" get of "plugins/Orion/checks.yml"
	set {autosneakchecks} to single value "Auto Sneak Checks" get of "plugins/Orion/checks.yml"
	set {multiaurachecks} to single value "Auto Sneak Checks" get of "plugins/Orion/checks.yml"
	#-------------------------
	# Settings variables
	#-------------------------
	set {antibot} to single value "Anti Bot" get of "plugins/Orion/settings.yml"
	set {maxping} to single value "Max Ping" get of "plugins/Orion/settings.yml"
	set {range} to single value "Kill Aura range" get of "plugins/Orion/settings.yml"
	set {maxclicks} to single value "Max Clicks per second" get of "plugins/Orion/settings.yml"
	set {eatticks} to single value "Max speed of eating (seconds)" get of "plugins/Orion/settings.yml"
	set {regenticks} to single value "Max speed of regenerating (seconds)" get of "plugins/Orion/settings.yml"
	set {fastbreakticks} to single value "Max speed of breaking blocks (seconds)" get of "plugins/Orion/settings.yml"
	set {fastplaceticks} to single value "Max speed of placing blocks (seconds)" get of "plugins/Orion/settings.yml"
	set {fastbowticks} to single value "Max speed of shooting arrows (seconds)" get of "plugins/Orion/settings.yml"
	set {speedblocks} to single value "Max speed of moving per second (blocks)" get of "plugins/Orion/settings.yml"
	set {antibot} to single value "Anti Bot" get of "plugins/Orion/settings.yml"

variables:
	{killaura.%player%} = 0
	{multichecker.%player%} = 0
	{multiaura.%player%} = 0
	{waittimer.%player%} = 0
	{dban.%player%} = false
	{set.%player%} = false
	{antikb.%player%} = 0
	{sneaking.%player%} = 0
	{fastplace.%player%} = 0
	{fastbreak.%player%} = 0
	{fastbow.%player%} = 0
	{fly.%player%} = 0
	{jesus.%player%} = 0
	{recieve.%player%} = true
	{banned.orion} = 0
	{orion.broadcast} = true
	{orion.enabled} = true
	{bhp.%player%} = 0
	{nofall.%player%} = 0
	#----
	{orion.killaura} = true
	{orion.fastbow} = true
	{orion.fly} = true
	{orion.jesus} = true
	{orion.speed} = false
	{orion.antikb} = true
	{orion.regen} = true
	{orion.eat} = true
	{orion.fastbb} = true
	{orion.phase} = true
	{orion.selfharm} = true
	{orion.banwave} = true
	{orion.bhp} = true
	{orion.autosneak} = true
	{orion.autoclicker} = true
	{orion.nofall} = true
	{autoclicker.%player%} = 0
	{highjump.%player%} = 0
	{orion.highjump} = true
	#----
	{orion.killaura.ban} = true
	{orion.autoclicker.ban} = true
	{orion.speed.ban} = true
	{orion.fly.ban} = true
	{orion.jesus.ban} = true
	{orion.fastbow.ban} = true
	{orion.fastbreak.ban} = true
	{orion.fastplace.ban} = true
	{orion.antikb.ban} = true
	{orion.autosneak.ban} = true

on load:
	if {orion.bantype} is not set:
		set {orion.bantype} to "banwave"
		stop

on join:
	if {set.%player%} is false:
		set {killaura.%player%} to 0
		set {multiaura.%player%} to 0
		set {set.%player%} to true
		set {antikb.%player%} to 0
		set {sneaking.%player%} to 0
		set {fastplace.%player%} to 0
		set {fastbreak.%player%} to 0
		set {fly.%player%} to 0
		set {jesus.%player%} to 0
		set {fastbow.%player%} to 0
		set {bhp.%player%} to 0
		set {highjump.%player%} to 0
		stop

on join:
	if player has permission "orion.notify":
		set {recieve.%player%} to true
		stop


on join:
	if {antibot} = "true":
		set {mov.%player%} to true
		wait 20 seconds
		if {mov.%player%} is true:
			kick the player due to "%{logo}% &2AntiBot &eKick!"
			stop
		else:
			stop

on any movement:
	if {mov.%player%} is true:
		clear {mov.%player%}

#=======================================================
#                  Orion | Anti-Cheat                  =
#                      Points Reset                    =
#=======================================================
every 3 minutes:
	loop all players:
		if {killaura.%loop-player%} > 0:
			remove 1 from {killaura.%loop-player%}
		if {multiaura.%loop-player%} > 0:
			remove 1 from {multiaura.%loop-player%}
		if {antikb.%loop-player%} > 0:
			remove 1 from {antikb.%loop-player%}
		if {sneaking.%loop-player%} > 0:
			remove 1 from {sneaking.%loop-player%}
		if {fastplace.%loop-player%} > 0:
			remove 1 from {fastplace.%loop-player%}
		if {fastbreak.%loop-player%} > 0:
			remove 1 from {fastbreak.%loop-player%}
		if {fly.%loop-player%} > 0:
			remove 1 from {fly.%loop-player%}
		if {jesus.%loop-player%} > 0:
			remove 1 from {jesus.%loop-player%}
		if {fastbow.%loop-player%} > 0:
			remove 1 from {fastbow.%loop-player%}
		if {phase.%loop-player%} > 0:
			remove 1 from {phase.%loop-player%}
		if {bhp.%loop-player%} > 0:
			remove 1 from {bhp.%loop-player%}
		wait 2 ticks
every 5 minutes:
	if {orion.bantype} = "judgemental":
		loop all players:
			if {injudgemental.%loop-player%} is not set:
				set {_ka} to {kachecks} parsed as number
				set {_akb} to {antikbchecks} parsed as number
				set {_sneak} to {sneakchecks} parsed as number
				set {_fp} to {fastplacechecks} parsed as number
				set {_fb} to {fastbreakchecks} parsed as number
				set {_fastbow} to {fastbowchecks} parsed as number
				set {_fly} to {flychecks} parsed as number
				set {_jesus} to {jesuschecks} parsed as number
				set {_phase} to {phasechecks} parsed as number
				set {_autoclicker} to {autoclickerchecks} parsed as number
				set {_speed} to {speedchecks} parsed as number
				wait 1 tick
				if {killaura.%loop-player%} > {_ka}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {antikb.%loop-player%} > {_akb}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {sneaking.%loop-player%} > {_sneak}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {fastplace.%loop-player%} > {_fp}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {fastbreak.%loop-player%} > {_fb}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {fly.%loop-player%} > {_fly}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {jesus.%loop-player%} > {_jesus}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {fastbow.%loop-player%} > {_fastbow}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {phase.%loop-player%} > {_phase}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				else if {bhp.%loop-player%} > {_speed}:
					add loop-player to {judgemental::*}
					set {injudgemental.%loop-player%} to true
				wait 2 ticks


#=======================================================
#                  Orion | Anti-Cheat                  =
#                      Commands                        =
#=======================================================

on join:
	if {ban.%player%} is set:
		set join message to ""
		kick player due to "%{ban.%player%}%"
		stop
	else:
		stop

on load:
	send "&f-----------------------------------------------" to console
	send "%{logo}% &7I am now ready to catch hackers!" to console
	send "&bMake sure to configure everything in game!" to console
	send "&bWith &d/Orion config &bcommand!" to console
	send "&7 " to console
	send "&b%{logo}% Orion AntiCheat Developed by OrionPvP" to console
	send "&f-----------------------------------------------" to console

command /Orion [<text>] [<offline player>] [<text>]:
	permission: orion.admin
	aliases: /ac, /anticheat, /orionac, /o
	trigger:
		if arg 1 is not set:
			message "%{help1}%"
			message "%{help2}%"
			message "%{help3}%"
			message "%{help4}%"
			message "%{help5}%"
			message "%{help6}%"
			message "%{help7}%"
			message "%{help8}%"
			message "%{help9}%"
			message "%{help10}%"
		if arg 1 is "help":
			message "%{help1}%"
			message "%{help2}%"
			message "%{help3}%"
			message "%{help4}%"
			message "%{help5}%"
			message "%{help6}%"
			message "%{help7}%"
			message "%{help8}%"
			message "%{help9}%"
			message "%{help10}%"
		if arg 1 is "debug":
			if {orion.debug.mode} is not set:
				set {orion.debug.mode} to true
				message "%{logo}% &fDebug mode &astarted&f..."
				stop
			else:
				clear {orion.debug.mode}
				message "%{logo}% &fDebug mode &cended&f..."
				stop
		if arg 1 is "ban":
			if arg 2 is set:
				if arg 3 is set:
					if arg 2 has permission "orion.bypass":
						message "%{logo}% %{cannotban}%"
					else:
						strike lightning effect at the arg 2
						set {_reason} to arg 3
						set {_date} to now
						set {_p} to "%player%"
						kick arg 2 due to "&2Banned on: &6%{_date}%%new line%&2Banned by: &6%{_p}%%new line%%{banmsg}% %{_reason}%%new line%%{banmsg2}%%new line%%new line%%{banmsg3}%"
						if {orionban} is "true":
							set {ban.%arg 2%} to "&2Banned on: &6%{_date}%%new line%&2Banned by: &6%{_p}%%new line%%{banmsg}% %{_reason}%%new line%%{banmsg2}%%new line%%new line%%{banmsg3}%"
						else:
							execute console command "%{customcmd}% %arg 2% %arg 3%"
							stop
						set {staffbanned.%arg 2%} to player
						if file "plugins/Orion/Banned" doesn't exists:
							create folder "plugins/Orion/Banned"
						if file "plugins/Orion/Banned/%arg 2%.yml" doesn't exists:
							create file "plugins/Orion/Banned/%arg 2%.yml"
						wait 1 tick
						set "%arg 2%" to "Banned for: %arg 3% | By: %player%" in yaml file "plugins/Orion/Banned/%arg 2%.yml"
						if {orion.broadcast} is true:
							broadcast "%{logo}% &a%arg 2% &ewas banned by &a%player% &efor &2%arg 3%"
						stop
				else:
					message "%{logo}% %{correct1}%"
					stop
			else:
				message "%{logo}% %{correct1}%"
				stop
		if arg 1 is "testkb":
			if arg 2 is set:
				set {_p} to "%arg 2%" parsed as player
				message "%{logo}% &7Starting &cAnti KB &7test on &a%{_p}%"
				wait 1 second
				set {_lp1} to location of {_p}
				push {_p} upwards at speed 0.3
				push {_p} backwards at speed 0.3
				set {_lp2} to location of {_p}
				if {_lp1} = {_lp2}:
					message "%{logo}% &a%{_p}% &7came out &c&lPOSITIVE for &cAntiKB&7!"
					message "&7Make sure to check few more times just in case!"
					stop
				else:
					message "%{logo}% &a%{_p}% &7came out &a&lNEGATIVE for &cAntiKB&7!"
					message "&7Make sure to check few more times just in case!"
					stop
		if arg 1 is "oban":
			if arg 2 is set:
				if arg 3 is set:
					if arg 2 has permission "orion.bypass":
						message "%{logo}% &2You cannot ban this player!"
					else:
						strike lightning effect at the arg 2
						set {_reason} to arg 3
						add 1 to {banned.orion}
						set {_p} to "Orion"
						kick arg 2 due to "&2Banned on: &6%{_date}%%new line%&2Banned by: &6%{_p}%%new line%%{banmsg}% %{_reason}%%new line%%{banmsg2}%%new line%%new line%%{banmsg3}%"
						if {orionban} is "true":
							set {ban.%arg 2%} to "&2Banned on: &6%{_date}%%new line%&2Banned by: &6%{_p}%%new line%%{banmsg}% %{_reason}%%new line%%{banmsg2}%%new line%%new line%%{banmsg3}%"
						else:
							execute console command "%{customcmd}% %arg 2% %arg 3%"
							stop
						set {staffbanned.%arg 2%} to "Orion"
						if file "plugins/Orion/Banned" doesn't exists:
							create folder "plugins/Orion/Banned"
						if file "plugins/Orion/Banned/%arg 2%.yml" doesn't exists:
							create file "plugins/Orion/Banned/%arg 2%.yml"
						wait 1 tick
						set "%arg 2%" to "Banned for: %arg 3% | By: Orion" in yaml file "plugins/Orion/Banned/%arg 2%.yml"
						if {orion.broadcast} is true:
							broadcast "%{logo}% &a%arg 2% &ewas banned by &3Orion &efor &2%arg 3%"
						stop
				else:
					message "%{logo}% %{correct1}%"
					stop
			else:
				message "%{logo}% %{correct1}%"
				stop
		if arg 1 is "kick":
			if arg 2 is set:
				if arg 3 is set:
					if arg 2 has permission "orion.bypass":
						message "%{logo}% %{cannotkick}%"
					else:
						kick arg 2 due to "%{logo}% &2You have been kicked by &e%player%! &aReason: &e%arg 3%"
						if {orion.broadcast} is true:
							broadcast "%{logo}% &a%arg 2% &ewas kicked by &a%player% &efor &2%arg 3%"
				else:
					message "%{logo}% %{correct5}%"
					stop
			else:
				message "%{logo}% %{correct5}%"
				stop
		if arg 1 is "reset" or "clear":
			if arg 2 is set:
				set {killaura.%arg 2%} to 0
				set {multiaura.%arg 2%} to 0
				set {antikb.%arg 2%} to 0
				set {sneaking.%arg 2%} to 0
				set {fastplace.%arg 2%} to 0
				set {fastbreak.%arg 2%} to 0
				set {fly.%arg 2%} to 0
				set {autoclicker.%arg 2%} to 0
				set {bhp.%arg 2%} to 0
				set {jesus.%arg 2%} to 0
				set {fastbow.%arg 2%} to 0
				set {banned.%arg 2%} to false
				clear {ban.%arg 2%}
				message "%{logo}% %{resetchecks}%"
				unban arg 2
				stop
			else:
				message "%{logo}% %{correct2}%"
				stop
		if arg 1 is "unban":
			if arg 2 is set:
				set {killaura.%arg 2%} to 0
				set {multiaura.%arg 2%} to 0
				set {antikb.%arg 2%} to 0
				set {sneaking.%arg 2%} to 0
				set {fastplace.%arg 2%} to 0
				set {fastbreak.%arg 2%} to 0
				set {autoclicker.%arg 2%} to 0
				set {bhp.%arg 2%} to 0
				set {fly.%arg 2%} to 0
				set {jesus.%arg 2%} to 0
				set {fastbow.%arg 2%} to 0
				set {banned.%arg 2%} to false
				clear {ban.%arg 2%}
				unban arg 2
				if {broadcastban} is true:
					broadcast "%{logo}% &a%arg 2% %{unbanned}%%player%!"
				else:
					message "%{logo}% &a%arg 2% was unbanned"
				stop
			else:
				message "%{logo}% %{correct3}%"
				stop
		if arg 1 is "ip":
			if arg 2 is set:
				set {_ip} to "%ip of arg 2%"
				message "%{logo}% &eIp: &b%{_ip}%"
				stop
			else:
				message "%{logo}% %{correct4}%"
				stop
		if arg 1 is "notify":
			if {recieve.%player%} is true:
				set {recieve.%player%} to false
				message "%{logo}% %{alertsfalse}%"
				stop
			else:
				set {recieve.%player%} to true
				message "%{logo}% %{alertstrue}%"
				stop
		if arg 1 is "bcast":
			broadcast "%{logo}% %arg 2%"
			stop
		if arg 1 is "banned":
			message "%{logo}% %{totalbanned}%%{banned.orion}%"
		if arg 1 is "check":
			if arg 2 is set:
				if {staffbanned.%arg 2%} is set:
					message "%{logo}% &a%arg 2% &eWas recently banned by: &a%{staffbanned.%arg 2%}%&e!"
					stop
				else:
					message "%{logo}% &2This player was not banned anytime recently!"
					stop
		if arg 1 is "config":
			wait 1 tick
			open chest with 3 row named "&eConfig" to player
			if {orion.bantype} is "banwave":
				set {_it1} to light green dye
				set {_it1name} to "&6&lBan Type &7[&a&lBanWave&7]"
			if {orion.bantype} is "judgemental":
				set {_it1} to orange dye
				set {_it1name} to "&6&lBan Type &7[&6&lJudgemental Day&7]"
			if {orion.bantype} is "info":
				set {_it1} to pink dye
				set {_it1name} to "&6&lBan Type &7[&d&lINFO&7]"
			if {orion.bantype} is "none":
				set {_it1} to red dye
				set {_it1name} to "&6&lBan Type &7[&c&lNONE&7]"
			wait 3 ticks
			if {orion.broadcast} is true:
				set {_it2} to emerald block
				set {_it2name} to "&6&lBroadcast &7[&a&lTRUE&7]"
			else:
				set {_it2} to redstone block
				set {_it2name} to "&6&lBroadcast &7[&2&lFALSE&7]"
			wait 3 ticks
			format slot 0 of player with gray stained glass pane to close
			format slot 1 of player with gray stained glass pane to close
			format slot 2 of player with gray stained glass pane to close
			format slot 3 of player with gray stained glass pane to close
			format slot 4 of player with gray stained glass pane to close
			format slot 5 of player with gray stained glass pane to close
			format slot 6 of player with gray stained glass pane to close
			format slot 7 of player with gray stained glass pane to close
			format slot 8 of player with gray stained glass pane to close
			#-
			format slot 9 of player with gray stained glass pane to close
			format slot 17 of player with gray stained glass pane to close
			#-
			format slot 18 of player with gray stained glass pane to close
			format slot 19 of player with gray stained glass pane to close
			format slot 20 of player with gray stained glass pane to close
			format slot 21 of player with gray stained glass pane to close
			format slot 23 of player with gray stained glass pane to close
			format slot 24 of player with gray stained glass pane to close
			format slot 25 of player with gray stained glass pane to close
			format slot 26 of player with gray stained glass pane to close
			#-
			format slot 10 of player with red stained glass pane to close
			format slot 12 of player with red stained glass pane to close
			format slot 14 of player with red stained glass pane to close
			format slot 16 of player with red stained glass pane to close
			format slot 11 of player with {_it2} named "%{_it2name}%" with lore "&7Enable/disable ban/kick broadcasts" to close then run [make player execute command "/orionconf bcast"]
			format slot 13 of player with iron sword named "&2Hack settings" with lore "&7Enable/disable hacks and edit them!" to close then run [make player execute command "/orionconf hacks"]
			format slot 15 of player with {_it1} named "%{_it1name}%" with lore "&7Change banning type" to close then run [make player execute command "/orionconf bantype"]
			format slot 22 of player with diamond block named "&7&lBan settings" with lore "&7Edit bans" to close then run [make player execute command "/orionconf banwsettings"]
		if arg 1 is "judgemental":
			if {orion.bantype} is "judgemental":
				if arg 2 is not set:
					broadcast "%{logo}% %{judgementalstart}%"
					execute console command "/judgementalorionstart"
					stop
				if arg 2 is "add":
					if arg 3 is set:
						set {_p} to "%arg 3%" parsed as offline player
						message "%{logo}% &aAdded"
						set {injudgemental.%{_p}%} to true
						stop
			else:
				message "%{logo}% %{judgementalfail}%"
				stop

command /judgementalorionstart:
	permission: admin
	trigger:
		loop {judgemental::*}:
			execute console command "orion oban %loop-value%"
			remove loop-value from {judgemental::*}
			wait 10 ticks
		wait 1 minute
		stop


command /check [<offline player>]:
	permission: orion.check
	usage: &2/check <player>
	trigger:
		if arg 1 is not set:
			message "&2/check <player>"
			stop
		if arg 1 is set:
			wait 1 tick
			loop all players:
				if loop-player's name is "%arg 1%":
					set {_tonl} to true
			open chest with 4 rows named "%arg 1%" to player
			set {_ka} to {killaura.%arg 1%}
			set {_fb} to {fastbow.%arg 1%}
			set {_fly} to {fly.%arg 1%}
			set {_jesus} to {jesus.%arg 1%}
			set {_speed} to {bhp.%arg 1%}
			set {_clicker} to {autoclicker.%arg 1%}
			set {_antikb} to {antikb.%arg 1%}
			wait 2 ticks
			if {_tonl} is not set:
				set {_online} to "&4&lFALSE"
			else:
				set {_online} to "&a&lTRUE"
			set {_points} to {_antikb} + {_clicker} + {_speed} + {_jesus} + {_fly} + {_fb} + {_ka}
			set {_points} to {_points} parsed as number
			wait 2 ticks
			if {_points} = 0:
				set {_l1} to green stained glass pane
				set {_l2} to green stained glass pane
				set {_l3} to green stained glass pane
				set {_l4} to green stained glass pane
				set {_l5} to green stained glass pane
				set {_l6} to green stained glass pane
			if {_points} >= 4:
				set {_l1} to green stained glass pane
				set {_l2} to green stained glass pane
				set {_l3} to yellow stained glass pane
				set {_l4} to yellow stained glass pane
				set {_l5} to yellow stained glass pane
				set {_l6} to yellow stained glass pane
			if {_points} >= 10:
				set {_l1} to green stained glass pane
				set {_l2} to green stained glass pane
				set {_l3} to yellow stained glass pane
				set {_l4} to yellow stained glass pane
				set {_l5} to yellow stained glass pane
				set {_l6} to red stained glass pane
			if {_points} >= 15:
				set {_l1} to green stained glass pane
				set {_l2} to green stained glass pane
				set {_l3} to yellow stained glass pane
				set {_l4} to yellow stained glass pane
				set {_l5} to red stained glass pane
				set {_l6} to red stained glass pane
			if {_points} >= 20:
				set {_l1} to green stained glass pane
				set {_l2} to yellow stained glass pane
				set {_l3} to yellow stained glass pane
				set {_l4} to red stained glass pane
				set {_l5} to red stained glass pane
				set {_l6} to red stained glass pane
			if {_points} >= 25:
				set {_l1} to yellow stained glass pane
				set {_l2} to yellow stained glass pane
				set {_l3} to yellow stained glass pane
				set {_l4} to red stained glass pane
				set {_l5} to red stained glass pane
				set {_l6} to red stained glass pane
			if {_points} >= 30:
				set {_l1} to yellow stained glass pane
				set {_l2} to yellow stained glass pane
				set {_l3} to red stained glass pane
				set {_l4} to red stained glass pane
				set {_l5} to red stained glass pane
				set {_l6} to red stained glass pane
			if {_points} >= 35:
				set {_l1} to yellow stained glass pane
				set {_l2} to red stained glass pane
				set {_l3} to red stained glass pane
				set {_l4} to red stained glass pane
				set {_l5} to red stained glass pane
				set {_l6} to red stained glass pane
			if {_points} >= 40:
				set {_l1} to red stained glass pane
				set {_l2} to red stained glass pane
				set {_l3} to red stained glass pane
				set {_l4} to red stained glass pane
				set {_l5} to red stained glass pane
				set {_l6} to red stained glass pane
			set {_pskul} to "%arg 1%" parsed as offline player
			#-----
			format slot 6 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 8 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 15 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 16 of player with redstone block named "&4&lBAN" with lore "&7Click to ban the player!" to close then run [make player execute command "/Orion ban %arg 1% Hacking"]
			format slot 17 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 24 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 25 of player with gold block named "&6&lKICK" with lore "&7Click to kick the player!" to close then run [make player execute command "/Orion kick %arg 1% Hacking"]
			format slot 26 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 33 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 34 of player with gray stained glass pane named "&0" with lore "&7" to close
			format slot 35 of player with gray stained glass pane named "&0" with lore "&7" to close
			#-----
			format slot 7 of player with {_pskul}'s skull named "&7%arg 1%" with lore "&7Online: &a%{_online}%" to close
			#-----{_antikb} + {_clicker} + {_speed} + {_jesus} + {_fly} + {_fb} + {_ka}
			format slot 5 of player with {_l6} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 14 of player with {_l6} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 23 of player with {_l6} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 32 of player with {_l6} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close

			format slot 13 of player with {_l5} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 22 of player with {_l5} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 31 of player with {_l5} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close

			format slot 12 of player with {_l4} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 21 of player with {_l4} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 30 of player with {_l4} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close

			format slot 20 of player with {_l3} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 29 of player with {_l3} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close

			format slot 19 of player with {_l2} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			format slot 28 of player with {_l2} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close

			format slot 27 of player with {_l1} named "&7Amount of checks:" with lore "&a%{_points}%||&7KillAura: &a%{_ka}%||&7AntiKB: &a%{_antikb}%||&7AutoClicker: &a%{_clicker}%||&7Speed: &a%{_speed}%||&7Jesus: &a%{_jesus}%||&7Fly: &a%{_fly}%||&7FastBow: &a%{_fb}%" to close
			#-----
			stop
command /orionbantest:
	trigger:
		message "%{orion.bantype}%"
		stop

command /orionconf [<text>] [<text>]:
	permission: orion.admin
	trigger:
		if arg 1 is "bcast":
			if {orion.broadcast} is true:
				message "%{logo}% &7Broadcasts for &2Banning&7/&eKicking &7have been turned &2OFF&7!"
				set {orion.broadcast} to false
				stop
			if {orion.broadcast} is false:
				message "%{logo}% &7Broadcasts for &2Banning&7/&eKicking &7have been turned &aON&7!"
				set {orion.broadcast} to true
				stop
		if arg 1 is "hacks":
			wait 5 ticks
			open chest with 2 rows named "&2Hacks" to player
			set {_gh} to "ghost" parsed as offline player
			wait 2 ticks
			format slot 0 of player with iron sword named "&2Kill Aura" with lore "&7Enabled: &b%{orion.killaura}%" to close then run [make player execute command "/orionconf enable killaura"]
			format slot 1 of player with bow named "&3Fast Bow" with lore "&7Enabled: &b%{orion.fastbow}%" to close then run [make player execute command "/orionconf enable fastbow"]
			format slot 2 of player with feather named "&bFly" with lore "&7Enabled: &b%{orion.fly}%" to close then run [make player execute command "/orionconf enable fly"]
			format slot 3 of player with water bucket named "&9Jesus" with lore "&7Enabled: &b%{orion.jesus}%" to close then run [make player execute command "/orionconf enable jesus"]
			format slot 4 of player with diamond boots named "&bSpeed/Bhop" with lore "&7Enabled: &b%{orion.bhp}%" to close then run [make player execute command "/orionconf enable speed"]
			format slot 5 of player with cobweb named "&2AntiKB" with lore "&7Enabled: &b%{orion.antikb}%" to close then run [make player execute command "/orionconf enable antikb"]
			format slot 6 of player with golden apple named "&dRegen" with lore "&7Enabled: &b%{orion.regen}%" to close then run [make player execute command "/orionconf enable regen"]
			format slot 7 of player with cooked beef named "&eFast Eat" with lore "&7Enabled: &b%{orion.eat}%" to close then run [make player execute command "/orionconf enable eat"]
			format slot 8 of player with golden pickaxe named "&bFast Build/Break" with lore "&7Enabled: &b%{orion.fastbb}%" to close then run [make player execute command "/orionconf enable fastbb"]
			format slot 9 of player with {_gh}'s skull named "&bPhase" with lore "&7Enabled: &b%{orion.phase}%" to close then run [make player execute command "/orionconf enable phase"]
			format slot 10 of player with wooden sword named "&bAuto Clicker" with lore "&7Enabled: &b%{orion.autoclicker}%" to close then run [make player execute command "/orionconf enable autoclicker"]
			format slot 11 of player with leather boots named "&bNo Fall" with lore "&7Enabled: &b%{orion.nofall}%" to close then run [make player execute command "/orionconf enable nofall"]
			format slot 11 of player with iron boots named "&bAuto Sneak" with lore "&7Enabled: &b%{orion.autosneak}%" to close then run [make player execute command "/orionconf enable autosneak"]
			format slot 12 of player with golden boots named "&bHigh Jump" with lore "&7Enabled: &b%{orion.highjump}%" to close then run [make player execute command "/orionconf enable highjump"]
			format slot 13 of player with wooden axe named "&bMulti Aura" with lore "&7Enabled: &b%{orion.multiaura}%" to close then run [make player execute command "/orionconf enable multiaura"]
		if arg 1 is "banwsettings":
			wait 5 ticks
			open chest with 2 rows named "&cBanwave" to player
			set {_gh} to "ghost" parsed as offline player
			wait 2 ticks
			format slot 0 of player with iron sword named "&2Kill Aura" with lore "&7Allowed: &b%{orion.killaura.ban}%" to close then run [make player execute command "/orionconf banw killaura"]
			format slot 1 of player with bow named "&3Fast Bow" with lore "&7Allowed: &b%{orion.fastbow.ban}%" to close then run [make player execute command "/orionconf banw fastbow"]
			format slot 2 of player with feather named "&bFly" with lore "&7Allowed: &b%{orion.fly.ban}%" to close then run [make player execute command "/orionconf banw fly"]
			format slot 3 of player with water bucket named "&9Jesus" with lore "&7Allowed: &b%{orion.jesus.ban}%" to close then run [make player execute command "/orionconf banw jesus"]
			format slot 4 of player with diamond boots named "&bSpeed/Bhop" with lore "&7Allowed: &b%{orion.speed.ban}%" to close then run [make player execute command "/orionconf banw speed"]
			format slot 5 of player with cobweb named "&2AntiKB" with lore "&7Allowed: &b%{orion.antikb.ban}%" to close then run [make player execute command "/orionconf banw antikb"]
			format slot 6 of player with golden pickaxe named "&eFast Break" with lore "&7Allowed: &b%{orion.fastbreak.ban}%" to close then run [make player execute command "/orionconf banw fastbreak"]
			format slot 7 of player with plank named "&bFast Place" with lore "&7Allowed: &b%{orion.fastplace.ban}%" to close then run [make player execute command "/orionconf banw fastplace"]
			format slot 8 of player with {_gh}'s skull named "&bPhase" with lore "&7Allowed: &b%{orion.phase.ban}%" to close then run [make player execute command "/orionconf banw phase"]
			format slot 9 of player with wooden sword named "&bAuto Clicker" with lore "&7Allowed: &b%{orion.autoclicker.ban}%" to close then run [make player execute command "/orionconf banw autoclicker"]
			format slot 10 of player with iron boots named "&bAuto Sneak" with lore "&7Allowed: &b%{orion.autosneak.ban}%" to close then run [make player execute command "/orionconf banw autosneak"]
			format slot 11 of player with wooden axe named "&bMulti Aura" with lore "&7Allowed: &b%{orion.multiaura.ban}%" to close then run [make player execute command "/orionconf banw multiaura"]
		if arg 1 is "bantype":
			if {orion.bantype} is "banwave":
				set {orion.bantype} to "judgemental"
				message "%{logo}% %{banningmode}%&6&lJudgemental"
				stop
			if {orion.bantype} is "judgemental":
				set {orion.bantype} to "info"
				message "%{logo}% %{banningmode}%&d&lINFO"
				stop
			if {orion.bantype} is "info" or "none":
				set {orion.bantype} to "banwave"
				message "%{logo}% %{banningmode}%&9&lBanWave"
				stop
		if arg 1 is "banw":
			if arg 2 is "killaura":
				if {orion.killaura.ban} is true:
					set {orion.killaura.ban} to false
					message "%{logo}% &2KillAura %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.killaura.ban} to true
					message "%{logo}% &2KillAura %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "fastbow":
				if {orion.fastbow.ban} is true:
					set {orion.fastbow.ban} to false
					message "%{logo}% &2FastBow %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.fastbow.ban} to true
					message "%{logo}% &2FastBow %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "fly":
				if {orion.fly.ban} is true:
					set {orion.fly.ban} to false
					message "%{logo}% &2Fly %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.fly.ban} to true
					message "%{logo}% &2Fly %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "jesus":
				if {orion.jesus.ban} is true:
					set {orion.jesus.ban} to false
					message "%{logo}% &2Jesus %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orionconf.jesus.ban} to true
					message "%{logo}% &2Jesus %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "speed":
				if {orionconf.speed.ban} is true:
					set {orion.speed.ban} to false
					message "%{logo}% &2Speed %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orionconf.speed.ban} to true
					message "%{logo}% &2Speed %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "antikb":
				if {orion.antikb.ban} is true:
					set {orion.antikb.ban} to false
					message "%{logo}% &2AntiKB %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.antikb.ban} to true
					message "%{logo}% &2AntiKB %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "fastbreak":
				if {orion.fastbreak.ban} is true:
					set {orion.fastbreak.ban} to false
					message "%{logo}% &2Fast Break %{hackoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.fastbreak.ban} to true
					message "%{logo}% &2Fast Break %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "fastplace":
				if {orion.fastplace.ban} is true:
					set {orion.fastplace.ban} to false
					message "%{logo}% &2Fast Place %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.fastplace.ban} to true
					message "%{logo}% &2Fast Place %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "phase":
				if {orion.phase.ban} is true:
					set {orion.phase.ban} to false
					message "%{logo}% &2Phase %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.phase.ban} to true
					message "%{logo}% &2Phase %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "autoclicker":
				if {orion.autoclicker.ban} is true:
					set {orion.autoclicker.ban} to false
					message "%{logo}% &2AutoClicker %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.autoclicker.ban} to true
					message "%{logo}% &2AutoClicker %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "autosneak":
				if {orion.autosneak.ban} is true:
					set {orion.autosneak.ban} to false
					message "%{logo}% &2AutoSneak %{bansettingsoff}%"
					execute player command "/orionconf banwsettings"
					stop
				else:
					set {orion.autosneak.ban} to true
					message "%{logo}% &2AutoSneak %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
			if arg 2 is "multiaura":
				if {orion.multiaura.ban} is true:
					set {orion.multiaura.ban} to false
					message "%{logo}% &2MultiAura %{bansettingsoff}%"
					execute player command "/orionf banwsettings"
					stop
				else:
					set {orion.multiaura.ban} to true
					message "%{logo}% &2MultiAura %{bansettingson}%"
					execute player command "/orionconf banwsettings"
					stop
		if arg 1 is "enable":
			if arg 2 is "killaura":
				if {orion.killaura} is true:
					set {orion.killaura} to false
					message "%{logo}% &2KillAura %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.killaura} to true
					message "%{logo}% &2KillAura %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "fastbow":
				if {orion.fastbow} is true:
					set {orion.fastbow} to false
					message "%{logo}% &2FastBow %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.fastbow} to true
					message "%{logo}% &2FastBow %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "highjump":
				if {orion.highjump} is true:
					set {orion.highjump} to false
					message "%{logo}% &2HighJump %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.highjump} to true
					message "%{logo}% &2HighJump %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "fly":
				if {orion.fly} is true:
					set {orion.fly} to false
					message "%{logo}% &2Fly %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.fly} to true
					message "%{logo}% &2Fly %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "jesus":
				if {orion.jesus} is true:
					set {orion.jesus} to false
					message "%{logo}% &2Jesus %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.jesus} to true
					message "%{logo}% &2Jesus %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "speed":
				if {orion.bhp} is true:
					set {orion.bhp} to false
					message "%{logo}% &2Speed %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.bhp} to true
					message "%{logo}% &2Speed %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "antikb":
				if {orion.antikb} is true:
					set {orion.antikb} to false
					message "%{logo}% &2AntiKB %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.antikb} to true
					message "%{logo}% &2AntiKB %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "regen":
				if {orion.regen} is true:
					set {orion.regen} to false
					message "%{logo}% &2Regen %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.regen} to true
					message "%{logo}% &2Regen %{hackon}%"
					execute player command "/orion hacks"
					stop
			if arg 2 is "multiaura":
				if {orion.multiaura} is true:
					set {orion.multiaura} to false
					message "%{logo}% &2MultiAura %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.multiaura} to true
					message "%{logo}% &2MultiAura %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "eat":
				if {orion.eat} is true:
					set {orion.eat} to false
					message "%{logo}% &2FastEat %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.eat} to true
					message "%{logo}% &2FastEat %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "fastbb":
				if {orion.fastbb} is true:
					set {orion.fastbb} to false
					message "%{logo}% &2Fast Build/Break %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.fastbb} to true
					message "%{logo}% &2Fast Build/Break %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "phase":
				if {orion.phase} is true:
					set {orion.phase} to false
					message "%{logo}% &2Phase %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.phase} to true
					message "%{logo}% &2Phase %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "autoclicker":
				if {orion.autoclicker} is true:
					set {orion.autoclicker} to false
					message "%{logo}% &2AutoClicker %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.autoclicker} to true
					message "%{logo}% &2AutoClicker %{hackon}%"
					execute player command "/orionconf hacks"
					stop
			if arg 2 is "autosneak":
				if {orion.autosneak} is true:
					set {orion.autosneak} to false
					message "%{logo}% &2AutoSneak %{hackoff}%"
					execute player command "/orionconf hacks"
					stop
				else:
					set {orion.autosneak} to true
					message "%{logo}% &2AutoSneak %{hackon}%"
					execute player command "/orionconf hacks"
					stop
#=======================================================
#                  Orion | Anti-Cheat                  =
#                      Kill Aura                       =
#=======================================================
on damage:
	if {orion.killaura} is true:
		set {_mp} to {maxping} parsed as number
		if attacker's ping < {_mp}:
			if attacker doesn't have permission "orion.bypass":
				if victim is a entity or a player:
					if victim is not a ender dragon:
						attacker is a player:
							if damage cause is not a projectile:
								if tool of the attacker is a bow or a snowball or a egg or a ender pearl or a fishing rod:
									stop
								else:
									if damage wasn't caused by thorns:
										add 1 to {dmg.%attacker%}
										set {_ka} to {range} parsed as number
										if distance between attacker and victim is greater than {_ka}:
											cancel event
											set {_p} to attacker's ping
											add 1 to {killaura.%attacker%}
											set {_dist} to distance between attacker and victim
											if {t.ka.lastcheck} is not set:
												set {t.ka.lastcheck} to now
											if difference between now and {t.ka.lastcheck} is higher than 1.5 seconds:
												loop all players:
													if loop-player has permission "orion.notify":
														if {recieve.%loop-player%} is true:
															set {t.ka.lastcheck} to now
															send "%{logo}% %{maincolor3}%%attacker% %{maincolor2}%(%{maincolor1}%Kill Aura%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{killaura.%attacker%}%Lv%{maincolor2}%) (%{maincolor1}%Range: &a%{_dist}% Blocks%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player
															if {orion.debug.mode} is true:
																set {_facing} to attacker's horizontal facing
																set {_tool} to attacker's tool
																set {_health} to attacker's health
																set {_damage} to damage
																send "&f&m-=-------------------------------=-" to loop-player
																send "&f[DEBUG] - Facing: &7%{_facing}% &f[&d✬&f]" to loop-player
																send "&f[DEBUG] - Item: &7%{_tool}% &f[&e⚔&f]" to loop-player
																send "&f[DEBUG] - Health: &7%{_health}% &f[&c❤&f]" to loop-player
																send "&f[DEBUG] - Damage: &7%{_damage}% &f[&4☠&f]" to loop-player
																send "&f&m-=-------------------------------=-" to loop-player



on damage:
	if tool of the attacker is a sword:
		attacker is blocking
		cancel event

#=======================================================
#                  Orion | Anti-Cheat                  =
#                     Auto Clicker                     =
#=======================================================

on left click:
	if {orion.autoclicker} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player's tool is shears:
					if targeted block is leaves:
						stop
				else:
					set {_t} to player's tool
					if player's tool is a shovel of efficiency:
						stop
					if player's tool is a shovel of efficiency 2:
						stop
					if player's tool is a shovel of efficiency 3:
						stop
					if player's tool is a shovel of efficiency 4:
						stop
					if player's tool is a shovel of efficiency 5:
						stop

					if player's tool is a pickaxe of efficiency:
						stop
					if player's tool is a pickaxe of efficiency 2:
						stop
					if player's tool is a pickaxe of efficiency 3:
						stop
					if player's tool is a pickaxe of efficiency 4:
						stop
					if player's tool is a pickaxe of efficiency 5:
						stop

					if player's tool is a axe of efficiency:
						stop
					if player's tool is a axe of efficiency 2:
						stop
					if player's tool is a axe of efficiency 3:
						stop
					if player's tool is a axe of efficiency 4:
						stop
					if player's tool is a axe of efficiency 5:
						stop
					else:
						if event-block is not double-tall grass or grass or red flower or yellow flower or 59 or 141 or 142 or sugar_cane_block:
							add 1 to {clicks.%player%}
							set {_clicks} to {maxclicks} parsed as number
							if {clicks.%player%} >= {_clicks}:
								cancel event
								set {_p} to player's ping
								set {_cps} to {clicks.%player%}
								set {_tar} to event-block
								add 1 to {autoclicker.%player%}
								loop all players:
									if loop-player has permission "orion.notify":
										if {recieve.%loop-player%} is true:
											send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Auto Clicker%{maincolor2}%) (%{maincolor1}%CPS: %{_cps}%%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{autoclicker.%player%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%) (%{maincolor1}%Target Block: %{_tar}%%{maincolor2}%)" to loop-player

every second:
	loop all players:
		set {clicks.%loop-player%} to 0
		wait 2 ticks

#=======================================================
#                  Orion | Anti-Cheat                  =
#                     Multi Aura                       =
#=======================================================
#on damage:
#	if {orion.multiaura} is true:
#		if attacker is player:
#			set {_mp} to {maxping} parsed as number
#			if attacker's ping < {_mp}:
#				if attacker's target is victim:
#					stop
#				else:
#					add 1 to {multiaura.%attacker%}
#					cancel event
#					loop all players:
#						if loop-player has permission "Orion.notify":
#							if {recieve.%loop-player%} is true:
#								send "%{logo}% %{maincolor3}%%attacker% %{maincolor2}%(%{maincolor1}%Multi Aura%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{multiaura.%attacker%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player
#=======================================================
#                  Orion | Anti-Cheat                  =
#                       Anti KB                        =
#=======================================================

on damage:
	if {orion.antikb} is true:
		if victim is a player:
			set {antitestkb.%victim%} to true
			set {_mp} to {maxping} parsed as number
			if victim's ping < {_mp}:
				if victim's health < victim's max health:
					if block at victim's location is not cobweb or cactus or lava or water:
						damage wasn't caused by lava, fire, burning, fall, poison or wither:
							victim is not riding:
								if victim's food level is not 0:
									victim doesn't have poison:
										victim doesn't have wither:
											victim isn't burning:
												wait 0.3 seconds
												if {antitestkb.%victim%} is true:
													victim isn't burning:
														set {_p} to victim's ping
														add 1 to {antikb.%victim%}
														loop all players:
															if loop-player has permission "Orion.notify":
																if {recieve.%loop-player%} is true:
																	send "%{logo}% %{maincolor3}%%victim% %{maincolor2}%(%{maincolor1}%Anti KB%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player

												else:
													stop
on any movement:
	if {antitestkb.%player%} is true:
		clear {antitestkb.%player%}
		stop
#=======================================================
#                  Orion | Anti-Cheat                  =
#                    Regen/Fast Eat                    =
#=======================================================
on heal:
	if {orion.regen} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player has regeneration:
					stop
				else:
					set {_dif} to difference between {heal.%player%} and now
					if {_dif} is less than 0.45 seconds:
						cancel event
						set {heal.%player%} to now
						loop all players:
							if loop-player has permission "orion.notify":
								if {recieve.%loop-player%} is true:
									send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Regen%{maincolor2}%) (%{maincolor1}%Healing speed: %{maincolor3}%%{_dif}%%{maincolor2}%)" to loop-player
					set {heal.%player%} to now

on consume:
	if {orion.eat} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player has saturation:
					stop
				else:
					set {_dif} to difference between {eat.%player%} and now
					if {_dif} is less than 1.60 seconds:
						cancel event
						set {eat.%player%} to now
						loop all players:
							if loop-player has permission "orion.notify":
								if {recieve.%loop-player%} is true:
									send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Fast Eat%{maincolor2}%) (%{maincolor1}%Eating speed: %{maincolor3}%%{_dif}%%{maincolor2}%)" to loop-player
					set {eat.%player%} to now

on consume:
	if {orion.debug.mode} is true:
		if player's name is "OrionPVP_":
			if {eaten.orionpvp_.%player%} is not set:
				set {eaten.orionpvp_.%player%} to now
				stop
			else:
				set {_difeat} to difference between {eaten.orionpvp_.%player%} and now
				broadcast "%{_difeat}%"
				clear {eaten.orionpvp_.%player%}
				stop

on heal:
	if {orion.debug.mode} is true:
		if player's name is "OrionPVP_":
			if {regen.orionpvp_.%player%} is not set:
				set {regen.orionpvp_.%player%} to now
				stop
			else:
				set {_difeat} to difference between {regen.orionpvp_.%player%} and now
				broadcast "%{_difeat}%"
				clear {regen.orionpvp_.%player%}
				stop
#=======================================================
#                  Orion | Anti-Cheat                  =
#                     Auto Sneak                       =
#=======================================================
on chat:
	if {orion.autosneak} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player is sneaking:
					add 1 to {sneaking.%player%}
					loop all players:
						if loop-player has permission "orion.notify":
							if {recieve.%loop-player%} is true:
								send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Auto Sneak%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{sneaking.%player%}%Lv%{maincolor2}%)" to loop-player
					stop

on command:
	if {orion.autosneak} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player is sneaking:
					add 1 to {sneaking.%player%}
					loop all players:
						if loop-player has permission "orion.notify":
							if {recieve.%loop-player%} is true:
								send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Auto Sneak%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{sneaking.%player%}%Lv%{maincolor2}%)" to loop-player
					stop

#=======================================================
#                  Orion | Anti-Cheat                  =
#                   Fast Place/Break                   =
#=======================================================
on place:
	if {orion.fastbb} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player's gamemode is survival:
					if event-block is not double-tall grass or grass or red flower or yellow flower or 59 or 141 or 142 or sugar_cane_block:
						set {_seconds} to "%{fastplaceticks}% seconds"
						set {_dif} to difference between {fastplacetest.%player%} and now
						if {_dif} is less than {_seconds}:
							cancel event
							add 1 to {fastplace.%player%}
							set {_p} to player's ping
							loop all players:
								if loop-player has permission "orion.notify":
									if {recieve.%loop-player%} is true:
										send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Fast Place%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{fastplace.%player%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%) (%{maincolor1}%Block: %{_p}%%event-block%)" to loop-player
						set {fastplacetest.%player%} to now
						stop

on break:
	if {orion.fastbb} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player doesn't have permission "orion.bypass":
				if player's gamemode is survival:
					if event-block is not double-tall grass or red flower or yellow flower or 59 or 141 or 142 or sugar_cane_block:
						set {_seconds} to "%{fastbreakticks}% seconds"
						set {_dif} to difference between {fastbreaktest.%player%} and now
						if {_dif} is less than {_seconds}:
							cancel event
							add 1 to {fastbreak.%player%}
							set {_p} to player's ping
							loop all players:
								if loop-player has permission "orion.notify":
									if {recieve.%loop-player%} is true:
										send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Fast Break%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{fastbreak.%player%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%) (%{maincolor1}%Block: %{_p}%%event-block%)" to loop-player
						set {fastbreaktest.%player%} to now
						stop


#=======================================================
#                  Orion | Anti-Cheat                  =
#                 	   Fly/Jesus          	           =
#=======================================================
on any movement:
	if {orion.fly} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player is not riding:
				if player doesn't have permission "orion.bypass":
					if player's gamemode is survival or adventure:
						if player's health < player's max health:
							if block under player is air:
								set {_b} to block under player
								if block under {_b} is air:
									set {_y1} to y-coordinates of player
									if block behind {_b} is air:
										if block 1 meter south of {_b} is air:
											if block 1 meter west of {_b} is air:
												if block 1 meter east of {_b} is air:
													if block 1 meter north of {_b} is air:
														wait 5 ticks
														set {_y2} to y-coordinates of player
														if {_y2} is higher than or equal to {_y1}:
															if difference between {_y2} and {_y1} is higher than 1.4:
																chestplate of player is neither a chestplate nor air:
																	stop
																else:
																	add 1 to {fly.%player%}
																	push player downwards at speed 1.2
																	if {t.fly.lastcheck} is not set:
																		set {t.fly.lastcheck} to now
																	set {_p} to player's ping
																	set {_block} to block under player
																	if difference between now and {t.fly.lastcheck} is higher than 1.5 seconds:
																		loop all players:
																			if loop-player has permission "orion.notify":
																				if {recieve.%loop-player%} is true:
																					set {t.fly.lastcheck} to now
																					send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Fly%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{fly.%player%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%) (%{maincolor1}%Block under: %{_block}%%{maincolor2}%)" to loop-player
																			if {fly.%player%} > 10:
																				remove 5 from {fly.%player%}
																				kick player due to "%{logo}% %{maincolor1}%Fly &ais not allowed!%new line%&cPlease turn off your hacks before re-login!%new line%%new line%%{banmsg3}%"

on any movement:
	if {orion.jesus} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player is not riding:
				if player doesn't have permission "orion.bypass":
					if player's gamemode is survival or adventure:
						if player is not sneaking:
							if block above player is air:
								set {_b} to block under player
								if block under {_b} is water:
									set {_y1} to y-coordinates of player
									set {_x1} to x-coordinates of player
									set {_z1} to z-coordinates of player
									set {_loc} to location of player
									if block behind {_b} is water:
										if block 1 meter south of {_b} is water:
											if block 1 meter west of {_b} is water:
												if block 1 meter east of {_b} is water:
													if block 1 meter north of {_b} is water:
														wait 5 ticks
														set {_y2} to y-coordinates of player
														set {_x2} to x-coordinates of player
														set {_z2} to z-coordinates of player
														set {_loc2} to location of player
														if {_y1} = {_y2}:
															if {_loc} = {_loc2}:
																stop
															else:
																if difference between {_x2} and {_x1} is less than 1:
																	if difference between {_z2} and {_z1} is less than 1:
																		stop
																if difference between {_z2} and {_z1} is less than 1:
																	if difference between {_x2} and {_x1} is less than 1:
																		stop
																else:
																	add 1 to {jesus.%player%}
																	if {t.jesus.lastcheck} is not set:
																		set {t.jesus.lastcheck} to now
																	set {_p} to player's ping
																	if difference between now and {t.jesus.lastcheck} is higher than 1.5 seconds:
																		loop all players:
																			if loop-player has permission "orion.notify":
																				if {recieve.%loop-player%} is true:
																					set {t.jesus.lastcheck} to now
																					send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Jesus%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{fly.%player%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player
																			if {jesus.%player%} > 10:
																				remove 5 from {jesus.%player%}
																				kick player due to "%{logo}% %{maincolor1}%Jesus &ais not allowed!%new line%&cPlease turn off your hacks before re-login!%new line%%new line%%{banmsg3}%"

#=======================================================
#                  Orion | Anti-Cheat                  =
#                     Fast Bow                         =
#=======================================================
on shoot:
	if {orion.fastbow} is true:
		set {_mp} to {maxping} parsed as number
		if shooter's ping < {_mp}:
			if shooter doesn't have permission "orion.bypass":
				if shooter's tool is bow:
					if {shot.%shooter%} is not set:
						set {shot.%shooter%} to now
						stop
					else:
						set {_seconds} to {fastbowticks} parsed as number
						set {_p} to shooter's ping
						set {_justshot} to difference between {shot.%shooter%} and now
						if difference between {shot.%shooter%} and now is less than 0.2 seconds:
							add 1 to {fastbow.%shooter%}
							cancel event
							loop all players:
								if loop-player has permission "orion.notify":
									if {recieve.%loop-player%} is true:
										send "%{logo}% %{maincolor3}%%shooter% %{maincolor2}%(%{maincolor1}%Fast Bow%{maincolor2}%) %{maincolor2}%(%{maincolor1}%%{fastbow.%shooter%}%Lv%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player
						clear {shot.%shooter%}

on shoot:
	if {orion.debug.mode} is true:
		if shooter's name is "Xenons":
			if shooter's tool is bow:
				if {shottest.%shooter%} is not set:
					set {shottest.%shooter%} to now
				else:
					set {_dif} to difference between now and {shottest.%shooter%}
					broadcast "%{_dif}%"
					clear {shottest.%shooter%}
					stop
#=======================================================
#                  Orion | Anti-Cheat                  =
#                   Bunny Hop/Speed                    =
#=======================================================

on any movement:
	if {orion.bhp} is true:
		set {_mp} to {maxping} parsed as number
		if player's ping < {_mp}:
			if player is not riding:
				if player doesn't have permission "orion.bypass":
					if player's gamemode is survival or adventure:
						if player's flight mode is false:
							if player has speed:
								stop
							else:
								set {_blocks} to {speedblocks} parsed as number
							if block under player is not air:
								set {speed.tp.%player%} to true
								set {_bhp1x} to x-coordinates of player
								wait 1 second
								set {_bhp2x} to x-coordinates of player
								wait 1 tick
								if {speed.tp.%player%} is not set:
									stop
								else:
									if block under player is not ice:
										if {t.bhp.lastcheck} is not set:
											set {t.bhp.lastcheck} to now
										set {_t} to difference between {_bhp1x} and {_bhp2x}
										set {_t2} to difference between {_bhp1y} and {_bhp2y}
										if {_t} > {_blocks}:
											add 1 to {bhp.%player%}
											set {_p} to player's ping
											clear {speed.tp.%player%}
											if difference between now and {t.bhp.lastcheck} is higher than 3 seconds:
												loop all players:
													if loop-player has permission "orion.notify":
														if {recieve.%loop-player%} is true:
															set {t.bhp.lastcheck} to now
															send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Speed%{maincolor2}%) %{maincolor2}%(%{maincolor1}%Lv%{bhp.%player%}%%{maincolor2}%) (%{maincolor1}%8+ Blocks/s%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player
										if {_2} > {_blocks}:
											add 1 to {bhp.%player%}
											set {_p} to player's ping
											if difference between now and {t.bhp.lastcheck} is higher than 3 seconds:
												loop all players:
													if loop-player has permission "orion.notify":
														if {recieve.%loop-player%} is true:
															set {t.bhp.lastcheck} to now
															send "%{logo}% %{maincolor3}%%player% %{maincolor2}%(%{maincolor1}%Speed%{maincolor2}%) %{maincolor2}%(%{maincolor1}%Lv%{bhp.%player%}%%{maincolor2}%) (%{maincolor1}%8+ Blocks/s%{maincolor2}%) (%{maincolor1}%Ping: %{_p}%%{maincolor2}%)" to loop-player
										if {bhp.%player%} > 30:
											remove 10 from {bhp.%player%}
											kick player due to "%{logo}% %{maincolor1}%Speed &ais not allowed!%new line%&cPlease turn off your hacks before re-login!%new line%%new line%%{banmsg3}%"

on teleport:
	if {speed.tp.%player%} is true:
		clear {speed.tp.%player%}
		stop
#=======================================================
#                  Orion | Anti-Cheat                  =
#                        Phase                         =
#=======================================================
#=======================================================
#                  Orion | Anti-Cheat                  =
#                      Ban Waves                       =
#=======================================================
on join:
	if {banned.%player%} is true:
		set join message to ""
		kick player due to "%{banmsg}%"
		stop

on quit:
	if {banned.%player%} is true:
		set quit message to ""
		stop

every 10 seconds:
	if {orion.bantype} = "banwave":
		loop all players:
			set {_ka} to {kachecks} parsed as number
			set {_akb} to {antikbchecks} parsed as number
			set {_sneak} to {sneakchecks} parsed as number
			set {_fp} to {fastplacechecks} parsed as number
			set {_fb} to {fastbreakchecks} parsed as number
			set {_fastbow} to {fastbowchecks} parsed as number
			set {_fly} to {flychecks} parsed as number
			set {_jesus} to {jesuschecks} parsed as number
			set {_phase} to {phasechecks} parsed as number
			set {_autoclicker} to {autoclickerchecks} parsed as number
			set {_speed} to {speedchecks} parsed as number
			set {_multi} to {multiaurachecks} parsed as number
			if {orion.killaura.ban} is true:
				if {killaura.%loop-player%} is greater than or equal to {_ka}:
					execute console command "Orion oban %loop-player% KillAura"
			if {orion.multiaura.ban} is true:
				if {multiaura.%loop-player%} is greater than or equal to {_multi}:
					execute console command "Orion oban %loop-player% MultiAura"
			if {orion.fastbow.ban} is true:
				if {fastbow.%loop-player%} is greater than or equal to {_fastbow}:
					execute console command "Orion oban %loop-player% FastBow"
			if {orion.antikb.ban} is true:
				if {antikb.%loop-player%} is greater than or equal to {_akb}:
					execute console command "Orion oban %loop-player% AntiKB"
			if {orion.sneak.ban} is true:
				if {sneak.%loop-player%} is greater than or equal to {_sneak}:
					execute console command "Orion oban %loop-player% AutoSneak"
			if {orion.fastplace.ban} is true:
				if {fastplace.%loop-player%} is greater than or equal to {_fp}:
					execute console command "Orion oban %loop-player% FastPlace"
			if {orion.fastbreak.ban} is true:
				if {fastbreak.%loop-player%} is greater than or equal to {_fb}:
					execute console command "Orion oban %loop-player% FastBreak"
			if {orion.fly.ban} is true:
				if {fly.%loop-player%} is greater than or equal to {_fly}:
					execute console command "Orion oban %loop-player% Fly"
			if {orion.jesus.ban} is true:
				if {jesus.%loop-player%} is greater than or equal to {_jesus}:
					execute console command "Orion oban %loop-player% Jesus"
			if {orion.phase.ban} is true:
				if {phase.%loop-player%} is greater than or equal to {_phase}:
					execute console command "Orion oban %loop-player% Phase"
			if {orion.autoclicker.ban} is true:
				if {autoclicker.%loop-player%} is greater than or equal to {_autoclicker}:
					execute console command "Orion oban %loop-player% AutoClicker/FastClicker"
			if {orion.speed.ban} is true:
				if {speed.%loop-player%} is greater than or equal to {_speed}:
					execute console command "Orion oban %loop-player% Speed/BHop"
			wait 2 ticks
	if {orion.bantype} = "info":
		loop all players:
			set {_ka} to {kachecks} parsed as number
			set {_akb} to {antikbchecks} parsed as number
			set {_sneak} to {sneakchecks} parsed as number
			set {_fp} to {fastplacechecks} parsed as number
			set {_fb} to {fastbreakchecks} parsed as number
			set {_fastbow} to {fastbowchecks} parsed as number
			set {_fly} to {flychecks} parsed as number
			set {_jesus} to {jesuschecks} parsed as number
			set {_phase} to {phasechecks} parsed as number
			set {_autoclicker} to {autoclickerchecks} parsed as number
			set {_speed} to {speedchecks} parsed as number
			set {_multi} to {multiaurachecks} parsed as number
			if {orion.killaura.ban} is true:
				if {killaura.%loop-player-1%} is greater than or equal to {_ka}:
					loop all players:
						if loop-player-2 has permission "Orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%KillAura%{maincolor2}%)" to loop-player-2
					clear {killaura.%loop-player-1%}
			if {orion.multiaura.ban} is true:
				if {multiaura.%loop-player-1%} is greater than or equal to {_multi}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%MultiAura%{maincolor2}%)" to loop-player-2
					clear {multiaura.%loop-player-1%}
			if {orion.fastbow.ban} is true:
				if {fastbow.%loop-player-1%} is greater than or equal to {_fastbow}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%FastAura%{maincolor2}%)" to loop-player-2
					clear {fastbow.%loop-player-1%}
			if {orion.antikb.ban} is true:
				if {antikb.%loop-player-1%} is greater than or equal to {_akb}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%AntiKB%{maincolor2}%)" to loop-player-2
					clear {antikb.%loop-player-1%}
			if {orion.sneak.ban} is true:
				if {sneak.%loop-player-1%} is greater than or equal to {_sneak}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%AutoSneak%{maincolor2}%)" to loop-player-2
					clear {sneak.%loop-player-1%}
			if {orion.fastplace.ban} is true:
				if {fastplace.%loop-player-1%} is greater than or equal to {_fp}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%FastPlace%{maincolor2}%)" to loop-player-2
					clear {fastplace.%loop-player-1%}
			if {orion.fastbreak.ban} is true:
				if {fastbreak.%loop-player-1%} is greater than or equal to {_fb}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%FastBreak%{maincolor2}%)" to loop-player-2
					clear {fastbreak.%loop-player-1%}
			if {orion.fly.ban} is true:
				if {fly.%loop-player-1%} is greater than or equal to {_fly}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%Fly%{maincolor2}%)" to loop-player-2
					clear {fly.%loop-player-1%}
			if {orion.jesus.ban} is true:
				if {jesus.%loop-player-1%} is greater than or equal to {_jesus}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%Jesus%{maincolor2}%)" to loop-player-2
					clear {jesus.%loop-player-1%}
			if {orion.phase.ban} is true:
				if {phase.%loop-player-1%} is greater than or equal to {_phase}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%Phase%{maincolor2}%)" to loop-player-2
					clear {phase.%loop-player-1%}
			if {orion.autoclicker.ban} is true:
				if {autoclicker.%loop-player-1%} is greater than or equal to {_autoclicker}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%FastClick%{maincolor2}%)" to loop-player-2
					clear {autoclicker.%loop-player-1%}
			if {orion.speed.ban} is true:
				if {speed.%loop-player-1%} is greater than or equal to {_speed}:
					loop all players:
						if loop-player-2 has permission "orion.notify":
							if {recieve.%loop-player-2%} is true:
								send "%{logo}% %{maincolor3}%%loop-player-1% %{maincolor2}%(%{maincolor3}%Most likely hacking: %{maincolor3}%Speed%{maincolor2}%)" to loop-player-2
					clear {speed.%loop-player-1%}
			wait 2 ticks


#=======================================================
#                  Orion | Anti-Cheat                  =
#                      Debug CMD                       =
#=======================================================
command /odebug [<text>] [<text>] [<text>]:
	trigger:
		if player has permission "orion.debug":
			if {orion.debug.mode} = true:
				if arg 1 is not set:
					message "&f-------------------"
					message "&f/odebug addpoints"
					message "&f/odebug hits"
					message "&f/odebug bow"
					message "&f-------------------"
				if arg 1 is "help":
					message "&f-------------------"
					message "&f/odebug addpoints"
					message "&f/odebug hits"
					message "&f/odebug bow"
					message "&f-------------------"
				if arg 1 is "hits":
					if {orion.debug.hits.msg} is not set:
						set {orion.debug.hits.msg} to true
						message "&f[ODEBUG]: Turning hit debug &aon&f..."
						stop
					else:
						clear {orion.debug.hits.msg}
						message "&f[ODEBUG]: Turning hit debug &coff&f..."
						stop
				if arg 1 is "bow":
					if {orion.debug.bow.msg} is not set:
						set {orion.debug.bow.msg} to true
						message "&f[ODEBUG]: Turning bow debug &aon&f..."
						stop
					else:
						clear {orion.debug.bow.msg}
						message "&f[ODEBUG]: Turning bow debug &coff&f..."
						stop
				if arg 1 is "addpoints":
					if arg 2 is not set:
						message "&f/odebug addpoints [feature] [points]"
						message "&fka, fb, akb, fly, jesus"
						stop
					if arg 2 is "ka":
						if arg 3 is set:
							add arg 3 to {killaura.%player%}
							message "&f[ODEBUG]: points added..."
							stop
						else:
							message "&f/odebug addpoints [feature] [points]"
							message "&fka, fb, akb, fly, jesus"
							stop
					if arg 2 is "fb":
						if arg 3 is set:
							add arg 3 to {fastbow.%player%}
							message "&f[ODEBUG]: points added..."
							stop
						else:
							message "&f/Odebug addpoints [feature] [points]"
							message "&fka, fb, akb, fly, jesus"
							stop
					if arg 2 is "akb":
						if arg 3 is set:
							add arg 3 to {antikb.%player%}
							message "&f[ODEBUG]: points added..."
							stop
						else:
							message "&f/odebug addpoints [feature] [points]"
							message "&fka, fb, akb, fly, jesus"
							stop
					if arg 2 is "fly":
						if arg 3 is set:
							add arg 3 to {fly.%player%}
							message "&f[ODEBUG]: points added..."
							stop
						else:
							message "&f/odebug addpoints [feature] [points]"
							message "&fka, fb, akb, fly, jesus"
							stop
					if arg 2 is "jesus":
						if arg 3 is set:
							add arg 3 to {jesus.%player%}
							message "&f[ODEBUG]: points added..."
							stop
						else:
							message "&f/odebug addpoints [feature] [points]"
							message "&fka, fb, akb, fly, jesus"
							stop
			else:
				message "%{logo}% &fOrion DEBUG mode is &cnot &factivated..."
				message "&7Please use /Orion debug on"
				stop
		else:
			message "%{logo}% &fDEBUG Permission &cDENIED"
			stop

on damage:
	if {orion.debug.hits.msg} is true:
		if attacker is a player:
			if damage cause is not projectile:
				if distance between attacker and victim is higher than or equal to 5:
					set {_dist} to distance between attacker and victim
					set {_damage} to damage
					set {_tool} to attacker's tool
					loop all players:
						if loop-player has permission "orion.notify":
							if {recieve.%loop-player%} is true:
								send "&f[ODEBUG]: &c%attacker%" to loop-player
								send " &fDistance: &c%{_dist}%" to loop-player
								send " &fTool: &c%{_tool}%" to loop-player
								send " &fDamage:: &c%{_damage}%" to loop-player

on damage:
	if {orion.debug.bow.msg} is true:
		if attacker is a player:
			if damage cause is projectile:
				if distance between attacker and victim is higher than or equal to 5:
					set {_dist} to distance between attacker and victim
					set {_damage} to damage
					set {_tool} to attacker's tool
					loop all players:
						if loop-player has permission "orion.notify":
							if {recieve.%loop-player%} is true:
								send "&f[ODEBUG]: &c%attacker%" to loop-player
								send " &fDistance: &c%{_dist}%" to loop-player
								send " &fTool: &c%{_tool}%" to loop-player
								send " &fDamage:: &c%{_damage}%" to loop-player
